[tool.semantic_release]
version_variable = [
    "version_info.py:__version__",
    "app_version.py:__version__"
]
branch = "main"
upload_to_pypi = false
build_command = ""
changelog_file = "CHANGELOG.md"
commit_parser = "conventional"
commit_author = "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
commit_message = "chore(release): {version} [skip ci]"

[tool.autopep8]
max_line_length = 100
in-place = true
aggressive = 2
recursive = true
exclude = [
    "__pycache__",
    "tests/__pycache__",
    "gui/__pycache__"
]
