name: Auto PR from dev to main

on:
  push:
    branches:
      - dev  # devブランチへのpush時にトリガー

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create PR from dev to main
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "main"
          pr_title: "Auto PR: dev → main"
          pr_body: |
            **devブランチからmainブランチへの自動PR**
            - トリガー: ${{ github.sha }}
            - 実行者: ${{ github.actor }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "auto-pr"
          pr_reviewer: ""
          delete-branch: false   # devブランチを削除しない
          update: true          # 既存のPRがあれば更新する
