name: Dev CI

on:
  push:
    branches: [dev]
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:
    branches: [dev]
    paths-ignore:
      - "docs/**"
      - "README.md"    

jobs:
  dev-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r development-requirements.txt

      - name: Run flake8
        run: flake8 .

      - name: Skip pytest
        if: true
        run: echo "Skipping pytest for dev branch"
