name: GitGuardian Scan

on:
  push:
    branches:
      - dev  # devブランチへのpush時に実行

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth:
