name: GitGuardian Scan

on:
  push:
    branches:
      - dev  # devブランチへのpush時に実行

jobs:
  scan:
  name: GitGuardian Scan  # ←これを追加！
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth:
