name: GitGuardian Scan

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  merge_group:

jobs:
  scan:
    name: GitGuardian Scan  # ←これを追加！
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth:
