name: Main CI

on:
  push:
    branches: [main]
    paths-ignore: 
      - "docs/**"
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore: 
      - "docs/**"
      - "README.md"

jobs:
  main-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r development-requirements.txt

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        
      - name: Run pytest
        run: python -m pytest

